import Head from 'next/head';
import styled from 'styled-components';
import type { NextPage } from 'next';
import Link from 'next/link';
import Loader from '../components/Loader';
import toast from 'react-hot-toast';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          <Link
            prefetch={false}
            href={{
              pathname: '/[username]',
              query: { username: 'jeffd23' },
            }}
          >
            Jeffs Profile
          </Link>
          <Loader show={false} />
        </Title>
        <button onClick={() => toast.success('hello toast')}>Toast Me</button>
      </Main>
    </>
  );
};

const Main = styled.main`
  display: grid;
  place-content: center;
`;

const Title = styled.h1`
  margin: 0;
  font-size: 4rem;
  text-align: center;
  text-decoration: none;

  a {
    color: ${({ theme }) => theme.colors.secondary};
    text-decoration: none;
    &:hover,
    :focus,
    :active {
      text-decoration: underline;
    }
  }
`;

export default Home;
